function checkpw(){var a=$("input#passwort1").val();$("input#passwort2").val()!=a?($("i#pwtext").text("Passw\u00f6rter stimmen nicht \u00fcberein!"),$("i#pwtext").css("background-color","red")):($("i#pwtext").text("Passw\u00f6rter - OK"),$("i#pwtext").css("background-color","green"));$("i#pwtext").css("color","white");$("i#pwtext").css("padding","5px")}
function checkmail(){var a=$("input#mail").val();/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.test(a)?($("i#mailtext").text("E-Mail Adresse - \u00dcberpr\u00fcfung ausstehend"),$("i#mailtext").css("background-color","orange"),$("i#mailtext").css("color","white"),$("i#mailtext").css("padding","5px"),$("tr#mailcodeinput").css("display","table-row")):($("i#mailtext").text("Die E-Mail Adresse ist fehlerhaft!"),$("i#mailtext").css("background-color","red"),$("i#mailtext").css("color","white"),$("i#mailtext").css("padding",
"5px"))}function checkname(){""!=$("input#name").val()?($("i#nametext").text("Name - OK"),$("i#nametext").css("background-color","green")):($("i#nametext").text("Der Name darf nicht leer sein!"),$("i#nametext").css("background-color","red"));$("i#nametext").css("color","white");$("i#nametext").css("padding","5px")}
function checkuser(){var a=$("input#user").val();""!=a?($("input#checku").val("nok"),$("i#usertext").text("Username -- \u00dcberpr\u00fcfung l\u00e4uft"),$("i#usertext").css("background-color","orange"),$("i#usertext").css("color","white"),$("i#usertext").css("padding","5px"),$.get(siteurl+"/ajax.php?addon=felogin&user="+a,function(a){"nok"==a?($("i#usertext").text("Username - Achtung, dieser Username ist schon vergeben!!"),$("i#usertext").css("background-color","red")):($("input#checku").val("ok"),
$("i#usertext").text("Username - OK"),$("i#usertext").css("background-color","green"))})):($("input#checku").val("ok"),$("i#usertext").text("(Username -- OK)"),$("i#usertext").css("background-color","green"))}
function sendcode(){var a=$("input#mail").val();$.get(siteurl+"/ajax.php?addon=felogin&mail="+a,function(a){"ok"==a?($("i#mailcodetext").html("Code versandt!"),$("i#mailcodetext").css("line-height","25px"),$("i#mailcodetext").css("background-color","orange"),$("i#mailcodetext").css("color","white"),$("i#mailcodetext").css("padding","5px"),$("button#nochmalcode").css("display","table-cell")):($("i#mailcodetext").text(" Die Anzahl an Versuchen ist beschr\u00e4nkt! "),$("i#mailcodetext").css("background-color",
"red"),$("i#mailcodetext").css("line-height","25px"),$("i#mailcodetext").css("color","white"),$("i#mailcodetext").css("padding","5px"))})}
function checkcode(){var a=encodeURIComponent($("input#mailcode").val());$.get(siteurl+"/ajax.php?addon=felogin&code="+a,function(a){"ok"==a?($("i#mailcodetext").text("Code - OK"),$("i#mailcodetext").css("background-color","green"),$("i#mailcodetext").css("color","white"),$("i#mailcodetext").css("line-height","25px"),$("i#mailcodetext").css("padding","5px"),$("button#nochmalcode").css("display","none"),$("input#checkm").val("ok"),$("i#mailtext").text("E-Mail Adresse - OK"),$("i#mailtext").css("background-color",
"green")):($("i#mailcodetext").text("Code fehlerhaft"),$("i#mailcodetext").css("background-color","red"),$("i#mailcodetext").css("line-height","25px"),$("i#mailcodetext").css("color","white"),$("i#mailcodetext").css("padding","5px"),$("button#nochmalcode").css("display","table-cell"))})}
function checkcaptcha(){var a=$("input#captcha").val();""!=a?($("input#checkc").val("nok"),$("i#captchatext").text("Captcha -- \u00dcberpr\u00fcfung l\u00e4uft"),$("i#captchatext").css("background-color","orange"),$("i#captchatext").css("color","white"),$("i#captchatext").css("padding","5px"),$.get(siteurl+"/ajax.php?addon=felogin&captcha="+a,function(a){"nok"==a?($("i#captchatext").text("Captcha - Achtung, Ihre Eingabe ist falsch!!"),$("i#captchatext").css("background-color","red")):($("input#checkc").val("ok"),
$("i#captchatext").text("Captcha - OK"),$("i#captchatext").css("background-color","green"))})):($("input#checkc").val("ok"),$("i#captchatext").text("(Captcha -- OK)"),$("i#captchatext").css("background-color","green"))}
function checksubmit(){var a=$("input#passwort1").val(),c=$("input#passwort2").val(),d=$("input#mail").val(),b=$("input#checku").val(),e=$("input#checkc").val(),f=$("input#checkm").val(),g=$("input#name").val();$("input#akzep").val();return 0==/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.test(d)||c!=a||""==a||"nok"==b||"nok"==e||"nok"==f||"nok"==b||""==g?!1:$("input#akzep").is(":checked")?($("input#passwort1").val(SHA1(a)),$("input#passwort2").val(" "),!0):!1};
